[package]
name = "tau-rt"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]  # ONLY cdylib. No rlib.

[dependencies]
polling = "3"
async-task = "4"
async-ffi = "0.5"
slab = "0.4"
concurrent-queue = "2"
